services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=suporte_crud'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3307:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
      
volumes:
  mysql_data:
